name: bc_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  numberpicker: ^0.1.7
  http: ^0.12.0
  intl: ^0.15.7
  flutter:
    sdk: flutter
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/images/Gigs_Icon.png
    - assets/images/Shop_Icon.png
    - assets/images/Gallery_Icon.png
    - assets/images/Profile_Icon.png
    - assets/images/Games_Icon.png

    - assets/images/white_tshirt.png
    - assets/images/white_bag.png 
    - assets/images/dont_want_to_dance.jpeg
    - assets/images/alchemist_game.png 
    - assets/images/quiz_game.png
    - assets/images/flappy_game.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  fonts:
    - family: RationalInteger
      fonts: 
        - asset: assets/fonts/RationalInteger.ttf
    - family: CarbonBlock
      fonts: 
        - asset: assets/fonts/CarbonBlock.ttf
    - family: Quarca
      fonts: 
        - asset: assets/fonts/QuarcaCondBold.ttf
        - asset: assets/fonts/QuarcaCondBook.ttf
        - asset: assets/fonts/QuarcaCondLight.ttf
    - family: Typolino
      fonts: 
        - asset: assets/fonts/Typolino.otf
    - family: Rockout
      fonts: 
        - asset: assets/fonts/Rockout.otf



  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
